alphagov/di-github-actions

sam/build-application/action.yml

As part of our tests of switching over to Node/Typescript for certain components of SPOT, we'd like to be able to enable the `--beta-features` flag on the SAM CLI.

[SPOT-548] Add beta features boolean

---

.github/workflows/test-beautify-branch-name.yml
.github/workflows/test-parse-parameters.yml
beautify-branch-name/action.yml
beautify-branch-name/transform-branch-name.sh
code-quality/check-shell-scripts/action.yml
code-quality/run-checkov/action.yml
parse-parameters/action.yml
parse-parameters/parse-params.sh
report-step-result/action.yml
report-step-result/append-to-step-summary.sh
sam/build-application/action.yml
sam/check-stacks-exist/action.yml
sam/check-stacks-exist/check-stacks-exist.sh
sam/delete-stacks/action.yml
sam/delete-stacks/delete-stacks.sh
sam/deploy-stack/action.yml
sam/get-stale-stacks/action.yml
sam/get-stale-stacks/filter-stacks.sh

The action can be used in other actions to decode key-value pair arguments. The output is a string that can be parsed into a regular bash array or an associative array.
- Use the parse params action in the `get-stale-stacks` action
Usage examples:
```yaml
parameters: hello=world | sky = blue
tags: |
myTag=myValue
otherTag = otherValue
```
Output:
```bash
"hello=world sky=blue"
"[myTag]=myValue [otherTag]=otherValue"
```
---
- Better booleans 
Let the switch env vars be passed through as booleans rather than strings, so they can be used in the scripts directly without having to check the value.

BAU: Add an action to parse key=value pair parameters

---

paas/delete-stale-apps/action.yml

Don't fail the job if an app has a missing upload event or fails to get deleted.
The app will get deleted if the event is missing. If the delete command fails, the job will continue running for other apps.

BAU: Make the PaaS cleanup job more robust

---

beautify-branch-name/action.yml
beautify-branch-name/transform-branch-name.sh

Dependabot generates branch names with slashes and full stops which are not allowed in stack names. Adding functionality to replace those characters with hyphens

BAU - Beautify dependabot branch names

---

.gitignore
sam/build-application/action.yml

Makes it possible to provide `true`/`false` for `disable-cache` in the build-application action. Defaults to `false` - leaving behaviour unchanged (cache is enabled by default).

BAU add no-cached option

---

code-quality/check-linting/action.yml

Always print report for ESLint as warnings may not be flagged as errors, but we always want to see them in the job summary.

BAU: Linting checks - add option to treat warnings as errors

---

code-quality/check-linting/action.yml

Don't fold the output in a log group.

BAU: Always show Prettier and ESLint log output in the console

---

aws/ecr/build-docker-image/action.yml
code-quality/check-linting/action.yml

[DFA-1400: Correctly filter files for ESLint](https://github.com/alphagov/di-github-actions/pull/26/commits/7642b66bdd782ec91106c2b6b699b5a244a2c41e)
The linting action was inadvertently including json files as grep would match the ".json" extension on the ".js" filter.
To solve this, construct a regex to check that the extension matches exactly.
[DFA-2213: Improvements to the build Docker image ECS action](https://github.com/alphagov/di-github-actions/commit/1cf34b5a693be4d0fca26056b6f3467527a4b505) 
- Optional auth to AWS
- Optional log-in to ECR
- Add outputs
- Check number of digests when reporting on the built image
This allows the workflows to be used as a step in another workflow that already has performed AWS and/or ECR auth, and which needs to re-use the input values.

DFA-2213 DFA-1400: Improvements to Docker image build and linting actions

---

.github/workflows/test-print-list-to-step-summary.yml
aws/ecr/build-docker-image/action.yml
aws/ecr/check-image-exists/action.yml
aws/ecr/get-image-digests/action.yml
aws/ecs/deregister-stale-task-definitions/action.yml
aws/ecs/deregister-stale-task-definitions/deregister-stale-task-definitions.sh
code-quality/check-linting/action.yml
paas/delete-stale-apps/action.yml
paas/delete-stale-apps/delete-stale-apps.sh
report-step-result/print-list/action.yml
scripts/aws/ecr/get-image-digests.sh
scripts/report-step-result/print-list.sh

**DFA-2213: Add an action to clean up stale ECS task definitions**
The action deregisters ECS task definitions that reference ECR images that no longer exist in the repository.
---
**Add action to print an array of values**
The action can print a list of values to a file or the step summary.
GitHub Flavored Markdown is used to produce output that can be displayed with formatting in GitHub Actions job summaries.
The script takes an optional message when there's only one element in the list. The script can substitute a token for the single value to print a customised message in that case.
---
**DFA-2213: Fixes to ECR docker actions**
- Use `sort -u` instead of `uniq` to correctly list uniqe images
- Move the logic to get image digests into a separate script that can be used in different …

DFA-2213: Clean up stale ECS task definitions

---

.github/workflows/check-pr.yaml
.github/workflows/test-deploy-to-paas.yml
aws/ecs/deregister-stale-task-definitions/action.yml
code-quality/run-checkov/action.yml
sam/check-stacks-exist/action.yml
sam/check-stacks-exist/check-stacks-exist.sh
sam/delete-stacks/action.yml
sam/delete-stacks/delete-stacks.sh
sam/get-stale-stacks/action.yml
sam/get-stale-stacks/filter-stacks.sh

**Fix checkov**
checkov errors if no checks are enabled since version `2.2.150`
This was happening since the action by default excluded the security framework so if there were no IaC (infrastructure as code) files in a PR, then no other frameworks would be enabled (e.g. CloudFormation) and the run would fail.
Instead, don't exclude the framework by default and add options to exclude specific frameworks and checks, as needed.
**Use the print list script to report job results** 
Use the `scripts/report-step-result/print-list.sh` script to report results instead of duplicating the logic across multiple scripts.
---
- Fix test failing due to random order of evaluating variables 
Sort the output file so we always get the same order

BAU: Fix checkov

---

code-quality/check-linting/action.yml
code-quality/check-shell-scripts/action.yml
code-quality/run-checkov/action.yml
code-quality/run-security-audit/action.yml

- Add an action to run npm security audit on a repository
- Add a step to run the AWS CloudFormation linter in the check linting action
- Correctly exit with an error status code when linting checks fail
The report action runs in a subshell and masks the pipe status. If a check fails, the script needs to explicitly exit with a non-zero code so the failure can surface up to the GitHub Actions interface.
- Correctly handle grep's non-zero exit status - 1 means no files found, otherwise exit with the error code returned

SSE-2463: Add npm audit action and run cfn-lint

---

aws/ecr/build-docker-image/action.yml
aws/ecr/check-image-exists/action.yml
aws/ecs/deregister-stale-task-definitions/action.yml
aws/ecs/deregister-stale-task-definitions/deregister-stale-task-definitions.sh
aws/ecs/register-task-definition/action.yml
scripts/aws/ecr/check-image-exists.sh
scripts/aws/ecr/get-image-digests.sh

**Split the `ecr/check-image-exists` action**
- Move the logic from the `ecr/check-image-exists` action ino a script.
- Use the script instead of the action in the repo to reduce internal dependencies and simplify the workflows.
---
- Optionally assume AWS role and login to ECR in the deregister stale tasks definitions action
Allow to pass in the AWS role ARN and the ECR repository name to the action.
- Add an action to render and register ECS task definition

SSE-2463: Improvements and additions to ECR/docker actions

---

sam/check-stacks-exist/action.yml
sam/delete-stacks/action.yml
scripts/aws/ecr/check-stacks-exist.sh

**Split the `sam/check-stack-exists` action**
Move the logic from the `sam/check-stack-exists` action ino a script. Use the script instead of the action in the repo to reduce internal dependencies and simplify the workflows.

SSE-2463: Split the sam/check-stack-exists action

---

.github/stubs/aws/stub-aws-cli.sh
aws/ecr/delete-docker-images/action.yml
code-quality/check-linting/action.yml
code-quality/check-shell-scripts/action.yml
code-quality/run-checkov/action.yml
sam/build-application/action.yml
sam/delete-stacks/action.yml
sam/delete-stacks/delete-stacks.sh
scripts/aws/sam/check-stacks-exist.sh

**Improvements to building SAM applications**
Add additional options to the `sam/build-application` action:
  - Disable parallel build
  - Set base directory to use for the build
  - Make AWS login optional if the role ARN is provided
  - Run additional validation on the SAM template
**Improvements to deleting SAM stacks**
Add functionality to the `sam/delete-stacks` action:
  - Add option to log into AWS if the role ARN is provided
  - Log stack names that were in a good state and ignored for deletion
  - Return ignored stacks with the output rather than printing to the console to fix a bug
**Fix issue with linting actions**
Fix a bug when jobs would always exit regardless of whether grep found matches.
This was caused by the `&& exit` appended to the end of the command that would be …

SSE-2496: Fixes and improvements for actions to build and delete stacks

---

aws/ecr/build-docker-image/action.yml
aws/ecr/check-image-exists/action.yml
aws/ecr/delete-docker-images/action.yml
aws/ecr/get-image-digests/action.yml
aws/ecs/deregister-stale-task-definitions/deregister-stale-task-definitions.sh
aws/ecs/register-task-definition/action.yml
aws/ssm/get-parameters/action.yml
scripts/aws/ecr/check-image-exists.sh

- Output resource URLs for ECS and ECR
Construct and return URLs of the pushed docker images and registered task definitions.
- Improve messages printed to the step summaries.
- Add the verbose option to the `aws/ecr/check-image-exists` action.
- Add an action to retrieve parameter values from SSM

SSE-2521: Add an action to retrieve SSM params

---

sam/deploy-stack/action.yml
scripts/parse-parameters.sh

Parse tags also when params are not present.
Exit from the parse params script if there are no values to parse.

SSE-2496: Fix bug in sam/deploy-stack action

---

.github/stubs/aws/stub-aws-cli.sh
.github/workflows/test-delete-stacks.yml
.github/workflows/test-get-ssm-parameters.yml
aws/ssm/get-parameters/action.yml

Add an option to exit with a status code if some params are missing, or to ignore the missing params and return whatever is found.
Adjust the stub AWS CLI to return an array for missing params

SSE-2521: Add an option to the get SSM params action to fail if params are missing

---

code-quality/check-linting/action.yml
sam/build-application/action.yml
scripts/aws/sam/validate-template.sh
secure-pipelines/upload-sam-package/action.yml

- Remove AWS login from the SAM build action
Authentication is not needed for building
Extend the action to take more options and perform more tasks
- Uploading SAM package
Provide a default value for the template
Optionally pull repo and download artifact before uploading
- Add a script to validate a SAM template

SSE-2685: Workflows to build SAM apps and upload to secure pipelines

---

scripts/aws/codepipeline/await-pipeline-execution.sh
scripts/aws/codepipeline/get-execution-id.sh
scripts/aws/codepipeline/get-pipeline-url.sh
scripts/secure-pipelines/get-artifact-version.sh
secure-pipelines/await-pipeline-execution/action.yml
secure-pipelines/deploy-application/action.yml
secure-pipelines/upload-sam-package/action.yml

**Add an action to await a secure pipeline execution for a given artifact version**
The action takes a pipeline name and an artifact ID and proceeds to:
1. Wait for the execution triggered by the artifact version to start
2. Wait for the execution to conclude and exits with an error code if the pipeline returns a failure result
**Add an action to deploy an application through secure pipelines**
The action uploads the artifact and then awaits the pipeline execution
---
- Remove default value for working directory as it is now optional in the di-devplatform-upload-action
- Construct pipeline URL when uploading a package to secure pipelines
- Output artifact version ID when uploading to secure pipelines

SSE-2685: Add workflows to deploy applications through secure pipelines

---

aws/ecr/build-docker-image/action.yml
aws/ecr/check-image-exists/action.yml

The password output should be masked if not used to prevent it from being logged.

BAU: Mask Docker ECR password

---

.github/workflows/test-beautify-branch-name.yml
scripts/transform-branch-name.sh

Ensure generated names don't end with a hyphen or underscore in the beautify branch name action

SSE-2649: Generate valid deployment names

---

scripts/aws/codepipeline/await-pipeline-execution.sh
scripts/aws/codepipeline/get-execution-id.sh
scripts/aws/codepipeline/start-pipeline-execution.sh
scripts/secure-pipelines/get-artifact-version.sh
secure-pipelines/await-pipeline-execution/action.yml
secure-pipelines/deploy-application/action.yml
secure-pipelines/deploy-fargate/action.yml
secure-pipelines/upload-sam-package/action.yml

Add an action to deploy to Fargate using secure pipelines
**Check if the artifact exists before uploading a SAM package to secure pipelines**
Upload the artifact if the artifact in the S3 bucket doesn't correspond to the current commit SHA.
Otherwise, don't upload and trigger a pipeline execution instead.

SSE-2685: Deploy to Fargate using secure pipelines

---

code-quality/run-checkov/action.yml

- use specific python version `3.11.6`
alphagov/di-github-actions/code-quality/run-checkov are all failing today due to one of the dependancies failing
and now It's started using python `3.12.0` version
But It to use Python 3.12 due to aiohttp and other dependencies not supporting 3.12 yet

Checkov GitHub Action fix
